name: Prepare Release Oxlint

on:
  workflow_dispatch:
  push:
    branches:
      - prepare-release-oxlint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  prepare_release:
    name: Prepare Release Oxlint
    uses: ./.github/workflows/reusable_prepare_release.yml
    with:
      name: oxlint
